### ISSUE TITLE
Question: Do you use empty salt?

### ISSUE THREAD

**Issue by microshine** [signalapp/libsignal-protocol-javascript#12]
entry point for HKDF function
https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/src/SessionCipher.js#L53-L55

HKDF function
https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/src/crypto.js#L42-L45

Sign function uses salt as key
https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/src/crypto.js#L42-L45

**Comment by moxie0** [comment]
Thanks @microshine but we don't use GitHub for questions, discusison, or support. Please see the mailing list or online community forums for discussion, thanks!
