### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sualko** [signalapp/libsignal-protocol-javascript#14]
Hi guys,

can someone explain why this lib is under such an, lets say, problematic to include license? I would like to add omemo to my chat app (jsxc/jsxc#228), but this is currently not possible because of the license. Is there a chance to dual-license this in any way?

Thank you in advance.

**Comment by moxie0** [comment]
Hey @sualko we don't use GitHub for discussion, questions, or support, just issue tracking. For general discussion with a community of folks, the [online forums](https://whispersystems.discoursehosting.net/) are your best bet, for questions or support there's support@whispersystems.org.  Thanks!
