### ISSUE TITLE
Why doesn't keyId accept strings?

### ISSUE THREAD

**Issue by tristanhoy** [signalapp/libsignal-protocol-javascript#15]
A uuid has a much stronger uniqueness guarantee than a randomly generated integer.

In fact, the public key itself has a much stronger uniqueness guarantee - which makes the keyId seem entirely superfluous.

**Comment by dangell7** [comment]
Where does keyId come from? How the heck did they use variables without declaring them?

**Comment by dangell7** [comment]
I guess they also created a new way to write JS?

**Comment by scottnonnenberg-signal** [comment]
You might consider looking at how the Desktop, iOS and Android apps deal with keys. They are created and registered with the server, always in order. An always-increasing integer is easy to manage - especially when debugging issues.

Please ask questions like this on the forums in the future: https://community.signalusers.org/
