### ISSUE TITLE
Potential bug in InMemorySignalProtocolStore

### ISSUE THREAD

**Issue by tristanhoy** [signalapp/libsignal-protocol-javascript#17]
On line 41, isTrustedIdentity returns TRUE if the identity is not found.

https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/test/InMemorySignalProtocolStore.js#L41

Either
a) this is a typo, and this function should reject unknown identities
b) there is no typo, and this is a "pinning" function that trusts all NEW identities and only rejects on id/key mismatch

Can you please clarify which is correct? The unit tests do not indicate which behaviour is expected in this scenario:

https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/test/IdentityKeyStore_test.js#L35

The wording of the error messages in lines 13 and 61 of SessionBuilder don't really make it clear either:

https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/src/SessionBuilder.js#L13
https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/src/SessionBuilder.js#L61

**Comment by liliakai** [comment]
This is [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use).

For reference, see https://github.com/WhisperSystems/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/state/impl/InMemoryIdentityKeyStore.java#L46
