### ISSUE TITLE
Simultaneous session initialization

### ISSUE THREAD

**Issue by stwiname** [signalapp/libsignal-protocol-javascript#18]
When 2 peers try to establish sessions with each other at the same time, they can end up with different sessions and unable to decrypt each others messages.

Scenario:
Alice creates a session from Bobs bundle. Bob does the same with Alice's bundle.
Alice receives a PreKeyWhisperMessage from Bob and processes it. This will then overwrite the previous session in Alice's store.
Bob also receives a PreKeyWhisperMessage from Alice and processes it. This will overwrite the previous session in Bob's store.

The end result is that Alice has a session to Bob that was initialized by Bob and Bob has a session to Alice that was initialized by Alice. Because they were established using different one time pre keys they are unable to exchange any messages other than what is in the PreKeyWhisperMessage ciphertext.

**Comment by liliakai** [comment]
A SessionRecord holds multiple sessions states, indexed by the initiator's ephemeral public key.

The only way what you describe would happen is if Alice and Bob chose identical values for their ephemeral keys.

**Comment by stwiname** [comment]
I get it. Had to have another read over the code.
