### ISSUE TITLE
Questions about libsignal for js

### ISSUE THREAD

**Issue by jonathanve** [signalapp/libsignal-protocol-javascript#2]
Hello, there

Congratulations. I've been waiting for signal protocol in js. I have some questions.
1. When I read the protocol, it says that generates multiple pre keys at install time. Does KeyHelper only generate one? generatePreKey is the only function I see. 
2. When reading the README.md, is keyId == registrationId?
3. I wrote this code to make it work (not wishful thinking here, I wanted to see it working):

``` javascript
  var KeyHelper = libsignal.KeyHelper;
  console.log(KeyHelper);

  // Store registrationId somewhere durable and safe.
  var registrationId = KeyHelper.generateRegistrationId();

  // is keyId == registrationId?
  var keyId = registrationId;

  var data = {};
  data.registrationId = registrationId;

  KeyHelper.generateIdentityKeyPair().then(function(identityKeyPair) {
    // keyPair -> { pubKey: ArrayBuffer, privKey: ArrayBuffer }
    // Store identityKeyPair somewhere durable and safe.
    data.identityKeyPair = identityKeyPair;
    return data;
  }).then(function(data) {
    return KeyHelper.generatePreKey(keyId);
  }).then(function(preKey) {
    //store.storePreKey(preKey.keyId, preKey.keyPair);
    data.preKey = preKey;
    return data;
  }).then(function(data) {
    return KeyHelper.generateSignedPreKey(data.identityKeyPair, keyId);
  }).then(function(signedPreKey) {
    //store.storeSignedPreKey(signedPreKey.keyId, signedPreKey.keyPair);
    data.signedPreKey = signedPreKey;

    // Register preKeys and signedPreKey with the server
    console.log(data.registrationId);
    console.log(data.identityKeyPair);
    console.log(data.preKey);
    console.log(data.signedPreKey);
  });
```

I would like to contribute, understanding the protocol now.

Thank you all

**Comment by liliakai** [comment]
1. yes
2. no

**Comment by cnanju** [comment]
Hi @liliakai  ,

```
       I am trying to use this lib , I to have a question similar to question no.2 above. 
```

 What is the keyId?
 Is it unique identifier of the user whose "public key types" (Identity Key Pair, Signed Key pair, One-time key pair) are supposed to be stored?

Thanks.

**Comment by richardaum** [comment]
It's very unclear to me also. What are `preKey` and how is should be handled? There's almost no information available.

**Comment by ghost** [comment]
@jonathanve @cnanju did have the same problem here (not with javascript, but with iOS - documentation is on all platforms unclear about that). I found out that `keyId ` is just a random generated id, nothing more. This id is not generated by the framework. You must generate an id by yourself. 

If you want to be super clear about how to generate the id, just load one of the open source projects (iOS, Java or Desktop) and search for the place where `generateSignedPreKey` is invoked.
