### ISSUE TITLE
Is this library still in development?

### ISSUE THREAD

**Issue by yuri-stepanov** [signalapp/libsignal-protocol-javascript#21]
Hi folks. 
I wanted to use this library for my next project and I wonder - there has be plenty of issues discover since the last commit (https://threatpost.com/breaking-signal-a-six-month-journey/124888/). Is there are plans to move forward with this library development?

**Comment by liliakai** [comment]
Currently this library only exists to support Signal-Desktop. We don't have the resources to develop and support it for general use.
