### ISSUE TITLE
How does the sender decrypts his own messages ?

### ISSUE THREAD

**Issue by hardik047** [signalapp/libsignal-protocol-javascript#23]
I am creating a secure chat app based on Signal protocol. The sender encrypts messages with receiver's keys and sends it to the server. The receiver can retrieve and decrypt the messages.

Now, we don't store the sent messages on the device after the sender logs out. So when logging in again, all his messages are retrieved again from the server.

Now, if only receiver can decrypt those messages how will the sender have his own messages decrypted?

**Comment by liliakai** [comment]
This question is one of service architecture design, which falls far outside the scope of libsignal-protocol. Perhaps someone on the community forums has time to help you: https://whispersystems.discoursehosting.net

**Comment by ninobaldo** [comment]
@hardik047 how you dig in signal js lib goes so far? Did you was able to put it to work? I am facing some problems with integration and I wondering if you make it
