### ISSUE TITLE
incompatible version number on PreKeyWhisperMessage

### ISSUE THREAD

**Issue by hardik047** [signalapp/libsignal-protocol-javascript#25]
I do not understand what went wrong. Can anyone guide me on this error?

Thanks a lot in advance.

**Comment by liliakai** [comment]
This isn't a support forum.  Please don't post questions here. If you need help, try the community forums: https://whispersystems.discoursehosting.net/

**Comment by hardik047** [comment]
Actually I digged in and found that this is happening because the encrypt function of SessionCipher returns a JSON object while decrypt function takes a bytebuffer as input. So the format is creating the issue. I guess there should be a solution from the library.

**Comment by danieltigse** [comment]
@hardik047 I kind of have the same error. So, how did you take a bytebuffer from the JSON object?
