### ISSUE TITLE
Unable to decrypt message sent by same user

### ISSUE THREAD

**Issue by akawtia** [signalapp/libsignal-protocol-javascript#26]
We are using https://github.com/WhisperSystems/libsignal-protocol-javascript in our chat application to encrypt messages end to end. We have an use case where we want to store encrypted messages on the server and retrieve them in the chat app.

In order to display the messages in the chat interface, we need to decrypt them. We are able to decrypt the messages the user received but not the messages which were sent by the user.

It is looking for the private key of the receiving user during decryption which is not available. Can you let us know if we are doing something wrong, can you help us resolve the issue.

**Comment by liliakai** [comment]
Sorry, but we don't have the resources to provide developer support for this library. Maybe someone on the community forums can help you.

**Comment by akawtia** [comment]
Can someone atleast tell if it is supported by the library??

**Comment by strugee** [comment]
@akawtia as @liliakai said, you really need to take this to the community. They're much better equipped to support you as WhisperSystems is very pressed for resources. https://whispersystems.discoursehosting.net/

**Comment by hardik047** [comment]
@akawtia Hey there. Can I contact you anyway? I'm stuck with the same library and maybe we can help each other.
