### ISSUE TITLE
identityKeyPair "empty" ?

### ISSUE THREAD

**Issue by danieltigse** [signalapp/libsignal-protocol-javascript#33]
Is it normal that the library gives me an "empty" ArrayBuffers inside identityKeyPair? I am using the example in the README file.

Look at the console.

<img width="1120" alt="screen shot 2017-11-08 at 9 57 17 am" src="https://user-images.githubusercontent.com/1870723/32555788-b0553664-c46b-11e7-9056-6e07b5f15715.png">

I am not able to make an encryption test. And I think this is the main issue. What am I doing wrong?

**Comment by dangell7** [comment]
What was your issue?
