### ISSUE TITLE
Webclient

### ISSUE THREAD

**Issue by ThraaxSession** [signalapp/libsignal-protocol-javascript#37]
Hi together :)

I am glad there there is a JS library for signal protocol, but wondered why there is no web reference client. (I know desktop client which is wrapped in electron, or better was) ... 

But it would be so much easier with a webclient. Could you enlighten me, why there is no web client?

Best regards
Gino

**Comment by scottnonnenberg** [comment]
This is not the place for discussions or questions. Please use the forums: https://whispersystems.discoursehosting.net/
