### ISSUE TITLE
'SessionBuilder' in Readme file

### ISSUE THREAD

**Issue by lacivert** [signalapp/libsignal-protocol-javascript#38]
I see this line on Readme file:

`SessionBuilder sessionBuilder = new libsignal.SessionBuilder(store, address);`

Is that a basic copy-paste fault from Java based other repository ?https://github.com/WhisperSystems/libsignal-protocol-java

**Comment by scottnonnenberg** [comment]
Probably. It'd be a super-quick PR if you wanna go fix it. :0)

**Comment by strugee** [comment]
@scottnonnenberg you might want to close this since your modified commit message didn't do it automatically :thumbsup:
