### ISSUE TITLE
How to define the "recipientId" and "deviceId"?

### ISSUE THREAD

**Issue by gouyuxiu** [signalapp/libsignal-protocol-javascript#4]
I don't know how to get the  "recipientId" and "deviceId".I need your help.

**Comment by empyreanx** [comment]
The Signal Protocol is designed to support multiple devices sharing a single account. The deviceId differentiates between these the devices. The recipientId is the user's identifier (could be a username or numerical value). Both the deviceId and recipientId are assigned by or negotiated with the server. If you're just testing things out you can the deviceId to 0 and the recipientId to any string you want.

**Comment by gouyuxiu** [comment]
I got it.Thank you for your reply very much.

------------------ 原始邮件 ------------------
发件人: "jrimclean";notifications@github.com;
发送时间: 2016年9月27日(星期二) 上午7:53
收件人: "WhisperSystems/libsignal-protocol-javascript"libsignal-protocol-javascript@noreply.github.com; 
抄送: "苟渝秀"1151992420@qq.com; "Author"author@noreply.github.com; 
主题: Re: [WhisperSystems/libsignal-protocol-javascript] How to define the"recipientId" and "deviceId"? (#4)

The Signal Protocol is designed to support multiple devices sharing a single account. The deviceId differentiates between these the devices. The recipientId is the user's identifier. Both the deviceId and recipientId are assigned by or negotiated by the server. If you're just testing things out you can just set the deviceId to 0 and the recipientId to any string you want.
