### ISSUE TITLE
Go api protocol for bridge

### ISSUE THREAD

**Issue by lil5** [signalapp/libsignal-protocol-javascript#55]
After searching from the best bridge I think I might have found it:
https://github.com/42wim/matterbridge/

**Issue**
https://github.com/42wim/matterbridge/issues/28
It seems it doesn't work on signal because there is no golang version.

I hope you all understand how fractured the IM chat apps have become after diverting from xmpp and that this may reunite people instead of isolate.

**Comment by scottnonnenberg-signal** [comment]
I think you'll need to provide a whole lot more background on this issue before I can really consider it. I feel like I must be missing some substantial context here.

**Comment by lil5** [comment]
If you look at the amount of various chats in the support room I think I might be able to make you understand:
- matrix: https://matrix.to/#/#matterbridge:matrix.org
- xmpp: <matterbridge@conference.jabber.de>
- gitter: https://gitter.im/42wim/matterbridge
- etc. There's more but these I'm not sure how to give links to. (Steam, Discord, Slack, Twitch, Mattermost)

> For a quick look check the Gitter link (doesn't require login)

If that doesn't help think about how many times you've felt/heard that we all are walking around with too many chat apps for no reason. It's coming down to the stage that this fragmentation is cutting connection rather than making them.

**Comment by lil5** [comment]
Ping: @42wim

**Comment by lil5** [comment]
:warning: **the repo linked seems only to handle the encryption** 

There is a Go Signal library: https://github.com/RadicalApp/libsignal-protocol-go
Although it is a bit old ( `Latest commit d09bcab on Apr 14, 2017` )

~~It would be great if this had official support from Open Whisper Systems.~~
