### ISSUE TITLE
Failure to decrypt if preKey or preKeyId is 0

### ISSUE THREAD

**Issue by pwoh** [signalapp/libsignal-protocol-javascript#56]
From the if-checks added in this commit:
https://github.com/signalapp/libsignal-protocol-javascript/commit/538c7aecceaa4fb2c27f1a105759c8f7c4cd0ac8

**Comment by scottnonnenberg-signal** [comment]
Doesn't seem like a bug to me.

**Comment by pwoh** [comment]
What are the expected or allowed values for preKey / preKeyId? Are they not integers?

**Comment by scottnonnenberg-signal** [comment]
1 is truthy, so that's a good place to start.
