### ISSUE TITLE
Encryption of Media Files

### ISSUE THREAD

**Issue by skrajath** [signalapp/libsignal-protocol-javascript#58]
Hi,
Encrypting simple messages is clean and straight as from the docs. What we couldn’t figure out is, encrypting media files (.pdf, .png, .jpeg etc).
Is there a way to do that in this lib? If so can someone point me how this can be achieved?
Sorry if there is a answer for this question already, but I couldn’t find one.

**Comment by moxie0** [comment]
We don't use GH issues for q&a, but you could try the forums
