### ISSUE TITLE
Protobuf error in electron application

### ISSUE THREAD

**Issue by McPo** [signalapp/libsignal-protocol-javascript#6]
Hi,

I am attempting to implement libsignal into an electron application.

I have created a basic html page which includes the library and generates a registration id. When opening the .html file from chrome, everything works fine.

However when I use electron to open the same html file in a new browser window. The alert with a registration id appears but I also notice two errors in the console.

Heres the HTML page

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>SaltIM</title>
        <script  type="text/javascript" src="./dist/libsignal-protocol.js"></script>
        <script type="text/javascript">
            var KeyHelper = libsignal.KeyHelper;
            var registrationId = KeyHelper.generateRegistrationId();
            alert(registrationId);
        </script>
    </head>
    <body>
        <a>Test libsignal</a>
    </body>
</html>
```

This is the error (Its repeated twice)

> libsignal-protocol.js:35490 Uncaught TypeError: Cannot read property 'loadProto' of undefined
> loadProtoBufs @ libsignal-protocol.js:35490
> (anonymous function) @ libsignal-protocol.js:35493
> (anonymous function) @ libsignal-protocol.js:35499
> (anonymous function) @ libsignal-protocol.js:36511

And heres the relevant section of code within libsignal

```
Internal.protobuf = function() {
    'use strict';

    function loadProtoBufs(filename) {
            console.log('dcodeIO', dcodeIO);
        return dcodeIO.ProtoBuf.loadProto(Internal.protoText['./src/protos/' + filename]).build('textsecure');
    }

    var protocolMessages = loadProtoBufs('WhisperTextProtocol.proto');

    return {
        WhisperMessage            : protocolMessages.WhisperMessage,
        PreKeyWhisperMessage      : protocolMessages.PreKeyWhisperMessage
    };
}();
```

Would you happen to have any advice as what the issue may be, so I can investigate further.

Thanks,
Emmet

**Comment by McPo** [comment]
I have just attempted to reproduce this issue in a minimal electron application, and it works fine. There is clearly an issue with my setup (Likely something webpack related). However any advice, such as where is Protobuf and dcodeIO initialised would still be greatly appreciated. (Such a question may be more suitable as a stack exchange post)

**Comment by McPo** [comment]
I have created the minimal project required to reproduce the issue.

```
git clone https://github.com/McPo/electron-quick-start.git
cd electron-quick-start
git checkout libsignal
npm install
npm start
```

It should take less than a minute to get it up and going.

You should notice the error messages in the console.
However if you open the index.html file in chrome, there should be no error messages.

**Comment by McPo** [comment]
dcodeIO appears to return ByteBuffer in Electron and a Protobuf in Chrome. Hence the undefined Protobuf in Electron. (This may be more relevant for the Electron repo, however I imagine other users would wish to use libsignal within an Electron app).

Electron
![image](https://cloud.githubusercontent.com/assets/1295034/18525847/1e4f62da-7ab6-11e6-9995-8abe8535362a.png)

Chrome
![image](https://cloud.githubusercontent.com/assets/1295034/18525856/2b88fa24-7ab6-11e6-8c45-8fc0f96be46d.png)

**Comment by liliakai** [comment]
The droids you are looking for are likely being attached to `module.exports` instead of `window`. Someday I hope we'll support a node-compatible build. Until then, you'll have to disable node integration in the renderer if you want to use this libaray as-is.

**Comment by McPo** [comment]
Thanks a lot for the help. Using the info you provided, I managed to get the script loading without the error messages, while maintaining node integration.

```
        <script>
            window.nodeRequire = require;
            delete window.require;
        </script>
        <script src="./node_modules/libsignal-protocol/dist/libsignal-protocol.js"></script>
        <script>
            window.require = window.nodeRequire;
            delete window.nodeRequire;
        </script>
```

I can confirm that it works end to end in electron now.
Again thanks a lot for the tip, it helped immensely.

Electron actually highlights such an issue in their FAQ http://electron.atom.io/docs/faq/.

**Comment by bastientanesie** [comment]
Thanks @McPo, you just saved me from a night of head-banging ^^'!

**Comment by marco-fp** [comment]
Thanks @McPo !
