### ISSUE TITLE
Why is there no nodejs implementation?

### ISSUE THREAD

**Issue by ericrange** [signalapp/libsignal-protocol-javascript#63]
Why is there no nodejs implementation?

**Comment by scottnonnenberg-signal** [comment]
This is not an issue. This is a discussion for the forums.

**Comment by ericrange** [comment]
a discussion? are you not interessted that people using your app? today we thought about a signal integration but gave up, after we found out that there is no working nodejs example, or any example that runs on backend.

**Comment by hamzahkhan** [comment]
@ericrange Any luck you found some resource in Nodejs?
