### ISSUE TITLE
Converse.js v4.2.0 unable send OMEMO message

### ISSUE THREAD

**Issue by danjde** [signalapp/libsignal-protocol-javascript#64]
Hi Dev!
I state that I don't know if this could be a libsignal bug, I've try to ask on Github [Converse.js without answer](https://github.com/conversejs/converse.js/issues/1524).

I've just installed (from git) on VPS Debian Stretch, Prosody 0.11, Fail2ban 0.9.6-2, Shorewall 5.0.15.6-1, Apache 2.4.25, modsecurity 3.0.0-3, php7 7.0.33, Converse.js v4.2.0, gitted libsignal-protocol-javascript and include it into converse html code.

I write just to understand if it could be a Libsingal or a Converse.js problem. If possible.

[Here](https://converse.3x1t.org/fullscreen.html) my Converse installation.

Thanks!

**Comment by scottnonnenberg-signal** [comment]
This is not the right place for that kind of discussion. You might find someone who can help you here: https://whispersystems.discoursehosting.net/

**Comment by danjde** [comment]
Thanks!

**Comment by chee** [comment]
@danjde did you have any luck?

**Comment by danjde** [comment]
No, I've try to write as suggested by @scottnonnenberg to [Signal Community](https://whispersystems.discoursehosting.net/t/converse-js-v4-2-0-unable-send-omemo-message/7474), with no luck.
It's a Converse 4.2.0 bug, surely.
I think the Converse.js developer will correct the problem even if [for now he doesn't answer](https://github.com/conversejs/converse.js/issues/1524#issuecomment-491380539)
I've add [a task on OMEMO](https://github.com/bascht/omemo-top/issues/138#issuecomment-489439973) too, where @licaon-kter says it works, although I have very serious doubts ;-)

**Comment by licaon-kter** [comment]
Yes it does, at least in 1:1, MUC might have issues, cleaning/regen keys might have others.

**Comment by chee** [comment]
`v4.2.0` does not work for me, when trying to send an OMEMO message the box remains greyed out. However, receiving OMEMO messages from the other user works fine. The error is `Error: Invalid signature` from `libsignal-protocol.min.js`. However, it works just fine on `v4.1.2`

**Comment by licaon-kter** [comment]
@chee can you try with the normal version instead of `.min.js`? Where did you get the minified one?

**Comment by danjde** [comment]
I've try with the "normal" version, not min.js, same result: don't start on OMEMO mode.

**Comment by licaon-kter** [comment]
Other clients work ok with OMEMO? Conversations? Dino? Gajim?

**Comment by danjde** [comment]
> licaon-kter: Other clients work ok with OMEMO? Conversations? Dino? Gajim?

Perfectly.
