### ISSUE TITLE
Install time Error "KeyId" not defined

### ISSUE THREAD

**Issue by dangell7** [signalapp/libsignal-protocol-javascript#71]
I copied the following code from the Install time section:

```
      var KeyHelper = libsignal.KeyHelper;

      var registrationId = KeyHelper.generateRegistrationId();
      // Store registrationId somewhere durable and safe.

      KeyHelper.generateIdentityKeyPair().then(function(identityKeyPair) {
        // keyPair -> { pubKey: ArrayBuffer, privKey: ArrayBuffer }
        // Store identityKeyPair somewhere durable and safe.
      });

      KeyHelper.generatePreKey(keyId).then(function(preKey) {
        store.storePreKey(preKey.keyId, preKey.keyPair);
      });

      KeyHelper.generateSignedPreKey(identityKeyPair, keyId).then(function(signedPreKey) {
        store.storeSignedPreKey(signedPreKey.keyId, signedPreKey.keyPair);
      });

      // Register preKeys and signedPreKey with the server
```

I receive an `Uncaught ReferenceError: keyId is not defined` error.

What is keyId and where does it come from?

**Comment by scottnonnenberg-signal** [comment]
You can see how the `keyId` is used here: https://github.com/signalapp/libsignal-protocol-javascript/blob/f5a838f1ccc9bddb5e93b899a63de2dea9670e10/src/KeyHelper.js#L39-L47

**Comment by dangell7** [comment]
STOP Pre-closing Issues! It's extremely rude. 

Your documentation doesn't work. Thats the definition an issue. It's not solved...  It's not closed.

I wonder how many other issues we closed with this attitude....

**Comment by scottnonnenberg-signal** [comment]
Submit a pull request to fix the documentation, if you believe it needs a change. When I look at that section of code, I don't think it should be expected to run if copy-pasted in its entirety. They are all async calls.
