### ISSUE TITLE
Is there a more detailed document or a demo actually used?

### ISSUE THREAD

**Issue by 1111mp** [signalapp/libsignal-protocol-javascript#76]
I really tried my best, and this knowledge is very difficult for me. According to the documentation, I don't know how to use it or where to start. Can someone help me?

**Comment by jcbrand** [comment]
If you're looking for an example app that uses this library, Converse.js uses it to implement OMEMO encryption for XMPP.
See here: https://github.com/conversejs/converse.js/blob/master/src/converse-omemo.js

Another app is JSXC which does the same:
https://github.com/jsxc/jsxc/tree/master/src/plugins/omemo

**Comment by 1111mp** [comment]
@jcbrand thank you very much.
