### ISSUE TITLE
Keepalive?

### ISSUE THREAD

**Issue by JsBergbau** [signalapp/libsignal-protocol-javascript#82]
https://github.com/gausma/nodered-contrib-signal-client This project uses libsignal. However after some time no messages are received anymore. When you restart the node, thus re-establish a connection, messages are received again. 
So I think it needs some keepalive. Is there support in your library or where should you begin with? Perhaps, then I take a look to detect dead connections and re-establish it.

Thanks for your support.

**Comment by scottnonnenberg-signal** [comment]
`libsignal-protocol-javascript` doesn't maintain any connections; it just processes incoming messages and encrypts outgoing messages. I'm going to close this.

**Comment by JsBergbau** [comment]
Thanks for the hint. Sorry, you're absolutely right. I mixed it up. The correct project is libsignal-service-javascript.
